import fs from "node:fs";
import path from "node:path";
import { AGENT_SPECS, shimNames, type Agent } from "./agents.ts";
import { agentDir, shimsDir } from "./paths.ts";
import { writeFileAtomic } from "./atomic.ts";

/**
 * Resolve a command on PATH, skipping tread's own shim directory so a shim
 * never re-execs itself.
 */
export function realBinary(name: string): string | null {
  const shims = shimsDir();
  for (const dir of (process.env.PATH ?? "").split(":")) {
    if (!dir || path.resolve(dir) === path.resolve(shims)) continue;
    const p = path.join(dir, name);
    try {
      fs.accessSync(p, fs.constants.X_OK);
      if (fs.statSync(p).isFile() || fs.lstatSync(p).isSymbolicLink()) return p;
    } catch {}
  }
  return null;
}

function script(name: string, agent: Agent, real: string | null): string {
  const spec = AGENT_SPECS[agent];
  const lines = [
    "#!/bin/sh",
    "# generated by tread — regenerate with `tread doctor --fix`",
    "",
    "# resolve the real binary, ignoring this shim directory",
    `real=${real ? JSON.stringify(real) : '""'}`,
    'if [ ! -x "$real" ]; then',
    `  real=$(PATH=$(printf '%s' "$PATH" | tr ':' '\\n' | grep -vxF "$(dirname "$0")" | paste -sd: -) command -v ${name})`,
    "fi",
    'if [ -z "$real" ]; then',
    `  echo "tread: cannot find the real ${name} on PATH" >&2`,
    "  exit 127",
    "fi",
    "",
    "# outside an environment, behave exactly like the real thing",
    'if [ -z "${TREAD_ENV_DIR:-}" ]; then',
    '  exec "$real" "$@"',
    "fi",
    "",
  ];

  if (spec.needsHome) {
    lines.push(
      "# this agent resolves part of its config through $HOME, so the env dir",
      "# has to become HOME for the agent process only. stash the real one so",
      "# a `tread` the agent shells out to can still find the user's home.",
      'TREAD_HOME="${TREAD_HOME:-$HOME}"',
      "export TREAD_HOME",
      'HOME="$TREAD_ENV_DIR"',
      "export HOME",
      "",
    );
  }
  for (const key of Object.keys(spec.envVars("X"))) {
    lines.push(`${key}="$TREAD_ENV_DIR/${spec.dir}"`, `export ${key}`);
  }

  // Resolved here rather than baked in by `tread`: one shim serves every
  // environment and finds out which one it is from $TREAD_ENV_DIR, so whether
  // this environment shares the login can only be answered at launch. A `test
  // -f` is the whole cost.
  const dirRef = `$TREAD_ENV_DIR/${spec.dir}`;
  const shared = spec.loginVars(dirRef, false);
  const isolated = spec.loginVars(dirRef, true);
  const loginKeys = Object.keys(shared);
  if (loginKeys.length > 0) {
    lines.push(
      "",
      "# this agent binds its stored login to its config dir, so each",
      "# environment would otherwise need its own. sharing is the default;",
      "# `tread` writes the marker file for an environment that opted out.",
      `if [ -f "$TREAD_ENV_DIR/.tread/isolate-login-${agent}" ]; then`,
      ...loginKeys.map((k) => `  ${k}="${isolated[k]}"`),
      "else",
      ...loginKeys.map((k) => `  ${k}="${shared[k]}"`),
      "fi",
      ...loginKeys.map((k) => `export ${k}`),
    );
  }

  lines.push("", 'exec "$real" "$@"', "");
  return lines.join("\n");
}

/** (Re)generate every shim. Idempotent. */
export function writeShims(): string[] {
  const dir = shimsDir();
  fs.mkdirSync(dir, { recursive: true });
  const written: string[] = [];
  for (const { name, agent } of shimNames()) {
    const target = path.join(dir, name);
    const body = script(name, agent, realBinary(name));
    const existing = fs.existsSync(target) ? fs.readFileSync(target, "utf8") : null;
    if (existing !== body) {
      // replace, never truncate-and-write: another shell may be exec'ing this
      // shim right now, and a half-written one is a broken interpreter line
      writeFileAtomic(target, body, 0o755);
      written.push(name);
    }
    fs.chmodSync(target, 0o755);
  }
  return written;
}

/**
 * Shims whose contents no longer match what tread would write.
 *
 * Comparing the whole body, not just whether the file is there and `real=`
 * resolves: after tread itself changes how a shim is generated — a new
 * isolation variable, an agent that now needs HOME moved — every existing
 * shim is silently out of date, and a check that only looked for missing
 * files would report a clean bill of health.
 */
export function shimDrift(): { name: string; state: "missing" | "stale" }[] {
  const dir = shimsDir();
  const out: { name: string; state: "missing" | "stale" }[] = [];
  for (const { name, agent } of shimNames()) {
    const p = path.join(dir, name);
    if (!fs.existsSync(p)) {
      out.push({ name, state: "missing" });
      continue;
    }
    if (fs.readFileSync(p, "utf8") !== script(name, agent, realBinary(name))) {
      out.push({ name, state: "stale" });
    }
  }
  return out;
}

/** True when every shim exists and matches what tread would generate today. */
export function shimsHealthy(): boolean {
  return shimDrift().length === 0;
}

export { agentDir };
