import fs from "node:fs";
import path from "node:path";
import { AGENTS, AGENT_SPECS, shimNames, type Agent } from "./agents.ts";
import { listEnvs } from "./env.ts";
import {
  agentDir, envDir, envsDir, envsDirSpellings, isUnder, realHome, shimsDir,
} from "./paths.ts";
import { writeFileAtomic } from "./atomic.ts";
import { backupStampFile } from "./backup.ts";

/**
 * The tread binary a shim should call back into.
 *
 * Baked in rather than resolved through PATH: the shim would otherwise have to
 * fork `command -v` on every launch to find out, and the one thing the backup
 * check may not do is cost anything on the launches where there is nothing to
 * do. `process.execPath` is the compiled binary in the installed case; running
 * from source it is bun, and the shim's own `[ -x "$tread" ]` guard then turns
 * the whole thing off — which is the right answer for a dev checkout, and what
 * keeps the generated text out of the tests' way.
 */
function treadBinary(): string {
  const p = process.env.TREAD_BIN ?? process.execPath;
  return path.basename(p) === "tread" ? p : "";
}

/** Single-quote a value for /bin/sh, closing and reopening around any quote. */
function shq(s: string): string {
  return `'${s.replaceAll("'", `'\\''`)}'`;
}

/**
 * Resolve a command on PATH, skipping tread's own shim directory so a shim
 * never re-execs itself — and any directory inside an environment, so one
 * environment's private copy never becomes the binary every shell runs.
 *
 * The second half is not hypothetical. kimi updating itself inside an
 * environment writes `<env>/.kimi-code/bin/kimi` and prepends that absolute
 * path to the shared `.zshrc`; the next `tread doctor --fix` resolved it ahead
 * of `~/.kimi-code/bin/kimi` and baked it into the one shim every environment
 * shares — a version nothing else asked for, and gone the moment that
 * environment is deleted.
 *
 * A candidate is refused for the same reason when it only *points* into an
 * environment: that is the same damage arriving through a shared directory
 * rather than through PATH, and `stray.ts` is what repairs it.
 */
/** Every file `name` needs at runtime is there and non-empty. */
function runnable(name: string, resolved: string): boolean {
  const agent = shimNames().find((s) => s.name === name)?.agent;
  const files = agent ? AGENT_SPECS[agent].runtimeFiles(resolved) : [resolved];
  return files.every((f) => {
    try {
      // An empty file is what a failed self-update leaves behind — claude's
      // updater writes the version file before it has the bytes, so a download
      // that dies leaves 0 bytes at the path the launcher already names.
      return fs.statSync(f).size > 0;
    } catch {
      return false;
    }
  });
}

export function realBinary(name: string): string | null {
  const shims = path.resolve(shimsDir());
  // resolved once, not per candidate: this runs for every entry on PATH
  const envs = envsDirSpellings();
  const inEnv = (p: string) => envs.some((d) => isUnder(p, d));
  for (const dir of (process.env.PATH ?? "").split(":")) {
    if (!dir) continue;
    const abs = path.resolve(dir);
    if (abs === shims || inEnv(abs)) continue;
    const p = path.join(abs, name);
    try {
      fs.accessSync(p, fs.constants.X_OK);
      if (!(fs.statSync(p).isFile() || fs.lstatSync(p).isSymbolicLink())) continue;
      const resolved = fs.realpathSync(p);
      if (inEnv(resolved)) continue;
      // Present and executable is not the same as runnable, and the difference
      // is the whole point for cursor-agent: the name on PATH is a launcher
      // script, and it is the `node` and `index.js` beside it that have to be
      // there. Reporting this one as healthy would also stop `doctor --fix`
      // restoring it, since nothing would look wrong.
      if (!runnable(name, resolved)) continue;
      return p;
    } catch {}
  }
  return null;
}

function script(name: string, agent: Agent, real: string | null): string {
  const spec = AGENT_SPECS[agent];
  const lines = [
    "#!/bin/sh",
    "# generated by tread — regenerate with `tread doctor --fix`",
    "",
    "# resolve the real binary, ignoring this shim directory and anything",
    "# inside an environment — one env's private copy is not everyone's binary",
    `real=${real ? JSON.stringify(real) : '""'}`,
    'if [ ! -x "$real" ]; then',
    `  real=$(PATH=$(printf '%s' "$PATH" | tr ':' '\\n' | grep -vxF "$(dirname "$0")" | awk -v e=${shq(envsDir() + path.sep)} 'index($0, e) != 1' | paste -sd: -) command -v ${name})`,
    "fi",
    'if [ -z "$real" ]; then',
    `  echo "tread: cannot find the real ${name} on PATH" >&2`,
    "  exit 127",
    "fi",
    "",
    // Above the early exec on purpose, so this runs whether or not an
    // environment is active. The loss it guards against is not an
    // environment's doing — a self-update failing in the real home leaves the
    // same 0-byte file either way — and $HOME is still the user's own here,
    // which the code below depends on.
    `# keep a copy of ${name} where ${name} cannot reach it: a failed self-update`,
    "# leaves an empty file where the binary was, and nothing left to run. The",
    "# copy is an APFS clone, so it costs no disk until the original changes.",
    `stamp=${shq(backupStampFile(agent))}`,
    `tread=${shq(treadBinary())}`,
    // every test here is a shell builtin, so a launch that has nothing to do
    // forks nothing at all. `-nt` alone is not enough: dash and zsh call
    // `file -nt <missing>` false, which would mean the first backup never runs.
    'if [ -s "$real" ] && [ -x "$tread" ] &&',
    '   { [ ! -e "$stamp" ] || [ "$real" -nt "$stamp" ]; }; then',
    // backgrounded, and that is the whole reason cursor can be covered at all:
    // cloning its 224MB version directory takes ~77ms, which is fine to spend
    // beside the agent and not fine to spend in front of it
    `  "$tread" _backup ${agent} "$real" >/dev/null 2>&1 &`,
    "fi",
    "",
    "# outside an environment, behave exactly like the real thing",
    'if [ -z "${TREAD_ENV_DIR:-}" ]; then',
    '  exec "$real" "$@"',
    "fi",
    "",
  ];

  if (spec.needsHome) {
    lines.push(
      "# this agent resolves part of its config through $HOME, so the env dir",
      "# has to become HOME for the agent process only. stash the real one so",
      "# a `tread` the agent shells out to can still find the user's home.",
      'TREAD_HOME="${TREAD_HOME:-$HOME}"',
      "export TREAD_HOME",
      'HOME="$TREAD_ENV_DIR"',
      "export HOME",
      "",
    );
  }
  for (const key of Object.keys(spec.envVars("X"))) {
    lines.push(`${key}="$TREAD_ENV_DIR/${spec.dir}"`, `export ${key}`);
  }

  // Only while an environment is active — the early exec above has already
  // taken the outside case, so updating from the real home is untouched. Every
  // one of these agents installs its update relative to a path a shim has
  // moved, so an update from in here either leaves a launcher in the real home
  // pointing at an environment (claude, cursor) or a second binary inside one
  // (kimi). See AgentSpec.noUpdate.
  const updateKeys = Object.keys(spec.noUpdate.vars);
  if (updateKeys.length > 0) {
    lines.push(
      "",
      `# ${name} installs its own updates relative to paths tread has moved, so an`,
      "# update from inside an environment lands there and outlives it. Updating",
      "# from outside still works, and is the only place it is safe.",
      ...updateKeys.map((k) => `${k}=${spec.noUpdate.vars[k]}`),
      `export ${updateKeys.join(" ")}`,
    );
  }

  // Resolved here rather than baked in by `tread`: one shim serves every
  // environment and finds out which one it is from $TREAD_ENV_DIR, so whether
  // this environment shares the login can only be answered at launch. A `test
  // -f` is the whole cost.
  const dirRef = `$TREAD_ENV_DIR/${spec.dir}`;
  const shared = spec.loginVars(dirRef, false);
  const isolated = spec.loginVars(dirRef, true);
  const loginKeys = Object.keys(shared);
  if (loginKeys.length > 0) {
    lines.push(
      "",
      "# this agent binds its stored login to its config dir, so each",
      "# environment would otherwise need its own. sharing is the default;",
      "# `tread` writes the marker file for an environment that opted out.",
      `if [ -f "$TREAD_ENV_DIR/.tread/isolate-login-${agent}" ]; then`,
      ...loginKeys.map((k) => `  ${k}="${isolated[k]}"`),
      "else",
      ...loginKeys.map((k) => `  ${k}="${shared[k]}"`),
      "fi",
      ...loginKeys.map((k) => `export ${k}`),
    );
  }

  // cursor is the one agent with no variable for the update switch, so the
  // shim types its flag for the user instead.
  const inject = spec.noUpdate.args.map(shq).join(" ");
  lines.push("");
  if (inject) {
    lines.push(
      `# ${name} installs its own updates relative to paths tread has moved, and`,
      "# offers no environment variable to stop it — a root option is the only",
      '# switch, and ahead of "$@" is where one is recognised: after a subcommand',
      "# name it would be the subcommand's to reject. This stops only the check a",
      "# session starts on its own; an explicit `update` still updates.",
      `exec "$real" ${inject} "$@"`,
    );
  } else {
    lines.push('exec "$real" "$@"');
  }
  lines.push("");
  return lines.join("\n");
}

/** (Re)generate every shim. Idempotent. */
export function writeShims(): string[] {
  const dir = shimsDir();
  fs.mkdirSync(dir, { recursive: true });
  const written: string[] = [];
  for (const { name, agent } of shimNames()) {
    const target = path.join(dir, name);
    const body = script(name, agent, realBinary(name));
    const existing = fs.existsSync(target) ? fs.readFileSync(target, "utf8") : null;
    if (existing !== body) {
      // replace, never truncate-and-write: another shell may be exec'ing this
      // shim right now, and a half-written one is a broken interpreter line
      writeFileAtomic(target, body, 0o755);
      written.push(name);
    }
    fs.chmodSync(target, 0o755);
  }
  return written;
}

/**
 * Shims whose contents no longer match what tread would write.
 *
 * Comparing the whole body, not just whether the file is there and `real=`
 * resolves: after tread itself changes how a shim is generated — a new
 * isolation variable, an agent that now needs HOME moved — every existing
 * shim is silently out of date, and a check that only looked for missing
 * files would report a clean bill of health.
 */
export function shimDrift(): { name: string; state: "missing" | "stale" }[] {
  const dir = shimsDir();
  const out: { name: string; state: "missing" | "stale" }[] = [];
  for (const { name, agent } of shimNames()) {
    const p = path.join(dir, name);
    if (!fs.existsSync(p)) {
      out.push({ name, state: "missing" });
      continue;
    }
    if (fs.readFileSync(p, "utf8") !== script(name, agent, realBinary(name))) {
      out.push({ name, state: "stale" });
    }
  }
  return out;
}

/** True when every shim exists and matches what tread would generate today. */
export function shimsHealthy(): boolean {
  return shimDrift().length === 0;
}

/**
 * A copy of an agent's own binary living inside an environment.
 *
 * The other half of `stray.ts`. There, an update inside an environment writes
 * through a *shared* directory, so it reaches the real home and what is left
 * behind is a link out here pointing in. An agent whose install root is one of
 * the *isolated* directories leaves nothing out here at all — the binary
 * simply lands in the environment, at whatever version that one session
 * happened to pull, and nothing about the real home looks wrong.
 *
 * It still escapes, which is the part worth catching: the installer prepends
 * the absolute path to the shared `.zshrc`, so every shell — inside any
 * environment or none — starts resolving to it, and deleting that environment
 * takes the user's agent with it.
 */
export interface InEnvBinary {
  agent: Agent;
  /** the environment it landed in */
  env: string;
  /** absolute path of the copy */
  path: string;
  /** bytes, because "180MB in an environment you forgot about" is the point */
  size: number;
  /** the copy outside every environment it displaces, or null if it is the only one */
  outside: string | null;
}

/** Every agent binary sitting inside an environment. */
export function findInEnvBinaries(): InEnvBinary[] {
  const out: InEnvBinary[] = [];
  for (const env of listEnvs()) {
    for (const agent of AGENTS) {
      const rel = AGENT_SPECS[agent].inEnvBin;
      if (!rel) continue;
      const p = path.join(envDir(env), rel);
      try {
        // lstat, not stat: a symlink here is `ensureSkeleton` pointing back at
        // the real home, which is the arrangement working rather than a leak
        const st = fs.lstatSync(p);
        if (!st.isFile()) continue;
        out.push({ agent, env, path: p, size: st.size, outside: realBinary(AGENT_SPECS[agent].bin) });
      } catch {}
    }
  }
  return out;
}

/**
 * Delete one, so the environment falls back to the shared install.
 *
 * Refused when there is nothing outside to fall back to — the same rule
 * `stray.ts` applies to a repair it cannot infer. tread removes the second
 * copy, never the only one; reinstall outside an environment first.
 */
export function removeInEnvBinary(b: InEnvBinary): boolean {
  if (!b.outside) return false;
  try {
    fs.rmSync(b.path, { force: true });
    // the directory only ever existed to hold this; leaving an empty `bin` on
    // PATH is how a shell keeps looking somewhere nothing will ever be again
    const dir = path.dirname(b.path);
    if (fs.readdirSync(dir).length === 0) fs.rmdirSync(dir);
    return true;
  } catch {
    return false;
  }
}

/**
 * PATH entries that point inside an environment.
 *
 * How one environment's copy becomes every shell's: the installer appends
 * `export PATH="<env>/.kimi-code/bin:$PATH"` to the *shared* `.zshrc`, with
 * `$HOME` already expanded to the environment root, so the line outlives both
 * the session and — unless someone notices — the environment.
 *
 * Reported with the file and line it came from, and never rewritten. A shell
 * rc is the user's own; `doctor` does not edit config it did not write. An
 * entry with no `source` is the current shell still carrying a line that has
 * already been removed, which a new shell fixes on its own.
 */
export interface EnvPathEntry {
  dir: string;
  /** the environment it falls inside */
  env: string;
  /** `file:line` of the rc line exporting it, when one can be found */
  source: string | null;
}

/** Shell rc files an environment shares, in the order a login shell reads them. */
const RC_FILES = [".zshenv", ".zprofile", ".zshrc", ".profile", ".bash_profile", ".bashrc"];

export function envPathEntries(): EnvPathEntry[] {
  const envs = envsDir();
  const active = process.env.TREAD_ENV_DIR ? path.resolve(process.env.TREAD_ENV_DIR) : null;
  const out: EnvPathEntry[] = [];
  const seen = new Set<string>();
  for (const dir of (process.env.PATH ?? "").split(":")) {
    if (!dir) continue;
    const abs = path.resolve(dir);
    if (!isUnder(abs, envs) || seen.has(abs)) continue;
    seen.add(abs);
    const source = rcSource(abs);
    // The active environment putting its own directories on this session's
    // PATH is the arrangement working, not a leak: claude does it for every
    // plugin that ships a binary. It starts mattering only once a shell rc has
    // persisted the path, because then every *other* shell gets it too — and
    // an entry naming some other environment is worth saying out loud either
    // way, rc line or not.
    if (source === null && active && isUnder(abs, active)) continue;
    out.push({ dir: abs, env: path.relative(envs, abs).split(path.sep)[0]!, source });
  }
  return out;
}

/** The `file:line` in the real home that exports `dir`, if one does. */
function rcSource(dir: string): string | null {
  for (const rel of RC_FILES) {
    const file = path.join(realHome(), rel);
    let text: string;
    try {
      text = fs.readFileSync(file, "utf8");
    } catch {
      continue;
    }
    // a plain substring: the line was written by an installer with the path
    // already expanded, so there is nothing to match structurally, and a
    // commented-out line naming it is worth showing anyway
    const lines = text.split("\n");
    const i = lines.findIndex((l) => l.includes(dir));
    if (i !== -1) return `${rel}:${i + 1}`;
  }
  return null;
}

export { agentDir };
